let cnt = document.getElementById("container");
//console.log(cnt);
cnt.style.backgroundColor = "yellow";
cnt.style.margin="20px";
cnt.style.padding="10px";
cnt.style.fontSize="18px";
cnt.style.color="blue";
cnt.style.fontWeight="bold";
cnt.style.height="200px";
cnt.style.width="300px";